---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-toml
          - id: check-added-large-files
    - repo: https://github.com/JohnnyMorganz/StyLua
      rev: v0.20.0
      hooks:
          - id: stylua
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
    - repo: https://github.com/hugoh/pre-commit-fish.git
      rev: v1.2
      hooks:
          - id: fish_syntax
          - id: fish_indent
