# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
  - type: standard
    ref: v4.285.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: cli/cli@v2.64.0
  - name: climech/grit@v0.3.0
  - name: BurntSushi/ripgrep@14.1.1
  - name: sharkdp/fd@v10.2.0
  - name: jqlang/jq@jq-1.7.1
  - name: ynqa/jnv@v0.4.2
  - name: dev.yorhel.nl/ncdu@2.5
  - name: zellij-org/zellij@v0.41.2
  - name: sharkdp/hyperfine@v1.19.0
  - name: XAMPPRocky/tokei@v12.1.2
  - name: bootandy/dust@v1.1.1
  - name: JohnnyMorganz/StyLua@v2.0.2
  - name: ClementTsang/bottom@0.10.2
  - name: svenstaro/genact@v1.4.2
  - name: golang/go@go1.23.4
  - name: starship/starship@v1.21.1
  - name: jesseduffield/lazygit@v0.44.1
  - name: junegunn/fzf@v0.57.0
  - name: mvdan/sh@v3.10.0
  - name: evilmartians/lefthook@v1.10.1
  - name: google/yamlfmt@v0.14.0
  - name: nushell/nushell@0.101.0
  - name: sharkdp/bat@v0.24.0
  - name: typst/typst@v0.12.0
  - name: Enter-tainer/typstyle@v0.12.14
  - name: neovim/neovim@v0.10.3
  - name: nektos/act@v0.2.71
  - name: dylanaraps/neofetch@7.1.0
  - name: dandavison/delta@0.18.2
  - name: volta-cli/volta@v2.0.2
  - name: evilmartians/lefthook@v1.11.3
  - name: google/yamlfmt@v0.16.0
  - name: eza-community/eza@v0.20.24
  - name: ynqa/jnv@v0.5.0
  - name: casey/just@1.40.0
  - name: hashicorp/terraform@v1.11.2
