# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
  - type: standard
    ref: v4.219.1 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: cli/cli@v2.56.0
  - name: climech/grit@v0.3.0
  - name: BurntSushi/ripgrep@14.1.1
  - name: sharkdp/fd@v10.2.0
  - name: jqlang/jq@jq-1.7.1
  - name: ynqa/jnv@v0.4.0
  - name: dev.yorhel.nl/ncdu@2.5
  - name: zellij-org/zellij@v0.40.1
  - name: sharkdp/hyperfine@v1.18.0
  - name: XAMPPRocky/tokei@v12.1.2
  - name: bootandy/dust@v1.1.1
  - name: JohnnyMorganz/StyLua@v0.20.0
  - name: ClementTsang/bottom@0.10.2
  - name: svenstaro/genact@v1.4.2
  - name: golang/go@go1.23.1
  - name: starship/starship@v1.20.1
  - name: jesseduffield/lazygit@v0.44.0
  - name: junegunn/fzf@v0.55.0
  - name: mvdan/sh@v3.9.0
  - name: evilmartians/lefthook@v1.7.15
  - name: google/yamlfmt@v0.13.0
  - name: nushell/nushell@0.97.1
  - name: sharkdp/bat@v0.24.0
