"$schema" = "https://starship.rs/config-schema.json"
command_timeout = 100

[container]
disabled = true

[directory]
truncation_length = 1000

[golang]
symbol = " "

[git_status]
conflicted = "🔀 "
format = "[$conflicted]($style)"
